import {and,eq,sql} from "drizzle-orm";
import {getChatGPTUser} from "../../chatgpt-auth";
import {getDb} from "../../../db";
import {arenaParticipants,arenas,profiles,topics,users} from "../../../db/schema";
const clean=(v:unknown,max:number)=>typeof v==="string"?v.trim().replace(/[<>]/g,"").slice(0,max):"";
async function player(){const identity=await getChatGPTUser();if(!identity)return null;const db=await getDb(),now=new Date().toISOString();await db.insert(users).values({id:identity.userId,email:identity.email,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:users.id,set:{email:identity.email,updatedAt:now}});await db.insert(profiles).values({userId:identity.userId,displayName:identity.fullName||identity.email.split("@")[0],avatar:(identity.fullName||identity.email).slice(0,2).toUpperCase(),updatedAt:now}).onConflictDoNothing();const [profile]=await db.select().from(profiles).where(eq(profiles.userId,identity.userId)).limit(1);return {identity,profile,db}}
async function roomCode(db:Awaited<ReturnType<typeof getDb>>){for(let i=0;i<8;i++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[n%32]).join("");const exists=await db.select({id:arenas.id}).from(arenas).where(eq(arenas.code,code)).limit(1);if(!exists.length)return code}throw new Error("Could not allocate room code")}
export async function GET(){try{const p=await player();if(!p)return Response.json({error:"Authentication required"},{status:401});return Response.json({topics:await p.db.select().from(topics)})}catch{return Response.json({error:"Arena service unavailable"},{status:503})}}
export async function POST(request:Request){try{const p=await player();if(!p)return Response.json({error:"Authentication required"},{status:401});const body=await request.json() as Record<string,unknown>,action=clean(body.action,10),now=new Date().toISOString();if(action==="join"){const code=clean(body.code,8).toUpperCase(),[arena]=await p.db.select().from(arenas).where(and(eq(arenas.code,code),eq(arenas.status,"lobby"))).limit(1);if(!arena)return Response.json({error:"Room code not found or battle already started"},{status:404});const [{count}]=await p.db.select({count:sql<number>`count(*)`}).from(arenaParticipants).where(eq(arenaParticipants.arenaId,arena.id));if(Number(count)>=arena.maxParticipants)return Response.json({error:"Arena is full"},{status:409});await p.db.insert(arenaParticipants).values({arenaId:arena.id,userId:p.identity.userId,displayName:p.profile.displayName,avatar:p.profile.avatar,joinedAt:now,lastSeenAt:now}).onConflictDoUpdate({target:[arenaParticipants.arenaId,arenaParticipants.userId],set:{status:"online",lastSeenAt:now,displayName:p.profile.displayName,avatar:p.profile.avatar}});return Response.json({code:arena.code})}const title=clean(body.title,40),topicId=Number(body.topicId),difficulty=clean(body.difficulty,12),questionCount=Math.min(20,Math.max(5,Number(body.questionCount)||10)),timeLimit=Math.min(120,Math.max(15,Number(body.timeLimit)||30)),visibility=body.visibility==="public"?"public":"private",maxParticipants=Math.min(20,Math.max(2,Number(body.maxParticipants)||8));if(title.length<3||!Number.isInteger(topicId))return Response.json({error:"Add a valid arena title and topic"},{status:400});const id=crypto.randomUUID(),code=await roomCode(p.db);await p.db.insert(arenas).values({id,code,hostId:p.identity.userId,title,topicId,difficulty:["easy","medium","hard"].includes(difficulty)?difficulty:"medium",questionCount,timeLimit,visibility,maxParticipants,createdAt:now,updatedAt:now});await p.db.insert(arenaParticipants).values({arenaId:id,userId:p.identity.userId,displayName:p.profile.displayName,avatar:p.profile.avatar,isHost:true,isReady:true,joinedAt:now,lastSeenAt:now});return Response.json({code},{status:201})}catch{return Response.json({error:"Unable to create or join arena"},{status:500})}}
