"use client";
import {useCallback,useEffect,useState} from "react";
import {RANKS,WHEEL_PRIZES} from "../../lib/ranks";
import RankBadge from "../components/RankBadge";
import s from "./rewards.module.css";
type Data={xp:number;level:number;rank:{name:string;xp:number};next:{name:string;xp:number}|null;spin:{prize:number;label:string}|null;events:{label:string;xp_delta:number;shards:number;created_at:string}[];loginClaimed:boolean;inactivityDue:string|null;serverNow:string;resetAt:number};
export default function Rewards(){const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[turn,setTurn]=useState(0),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/progression"),d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error||"Could not load rewards");setData(d);return d},[]);
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
 useEffect(()=>{const refresh=()=>{void load().catch(e=>setMessage(e.message))};window.addEventListener("focus",refresh);const delay=data?Math.max(1000,data.resetAt-Date.parse(data.serverNow)+1000):86400000;const timer=setTimeout(refresh,Math.min(delay,86401000));return ()=>{window.removeEventListener("focus",refresh);clearTimeout(timer)}},[load,data]);
 async function spin(){setBusy(true);setMessage("");try{const r=await fetch("/api/progression",{method:"POST"}),d=await r.json() as {error?:string;reward:{prize:number;label:string};alreadyClaimed:boolean};if(!r.ok)throw Error(d.error);const destination=360-d.reward.prize*60-30;setTurn(previous=>Math.ceil(previous/360)*360+1800+destination);setMessage(d.alreadyClaimed?`Already claimed today: ${d.reward.label}`:`Won ${WHEEL_PRIZES[d.reward.prize].label}! Your prize has been saved.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Spin failed. Retry to check your saved prize.")}finally{setBusy(false)}}
 return <><div className={s.top}>{data?<><RankBadge xp={data.xp}/><div className={s.rankProgress}><strong>{data.xp.toLocaleString()} XP</strong><span>{data.next?`${data.next.xp-data.xp} XP to ${data.next.name}`:"MASTERPIECE · Highest rank achieved"}</span><progress aria-label="Progress to next rank" max={data.next?data.next.xp-data.rank.xp:1} value={data.next?data.xp-data.rank.xp:1}/></div><div className={s.login}><b>+30 XP · Daily sign-in</b><span>{data.loginClaimed?"Today's bonus is in your account":"Awarded when you sign in"}</span><small>Resets at 00:00 UTC</small></div></>:<p>Loading your rank…</p>}</div>
 <div className={s.columns}><section className={s.wheelCard}><span className={s.eyebrow}>ONE FREE SPIN EACH DAY</span><h2>The Wheel of Fortune</h2><div className={s.wheelWrap}><span className={s.pointer} aria-hidden="true">▼</span><div className={s.wheel} style={{transform:`rotate(${turn}deg)`}} aria-hidden="true">{WHEEL_PRIZES.map((p,i)=><span className={s.sector} key={p.label} style={{transform:`rotate(${i*60+30}deg)`}}><b>{p.label}</b></span>)}</div><span className={s.hub} aria-hidden="true">♛</span></div><button className="btn cyan solid" disabled={!data||busy||!!data.spin} onClick={spin}>{busy?"Claiming prize…":data?.spin?"Today's spin claimed":"Spin the wheel"}</button><p className={s.status} role="status">{message||(data?.spin?data.spin.label:"Six prizes. Each has an equal 1-in-6 chance.")}</p>{data?.spin&&<small>Next spin: {new Date(data.resetAt).toISOString().slice(0,16).replace("T"," ")} UTC</small>}<ul className={s.prizes}>{WHEEL_PRIZES.map(p=><li key={p.label}>{p.label}</li>)}</ul><p>Free in-game rewards only. No purchases or cash value.</p></section>
 <aside className={s.rules}><span className={s.eyebrow}>KNOW THE RULES</span><h2>Protect your progress</h2><article><b>Sign in · +30 XP</b><p>Once per UTC day, including your first account registration. Signing out and back in does not award it twice.</p></article><article><b>Failed challenge · −20% of its reward</b><p>Rounded up. Charged once per challenge per UTC day. Further retries that day are free. A first-time successful solve still earns its full reward.</p></article><article><b>48 hours inactive · −200 XP</b><p>One penalty per inactive period, applied on the next platform request. Submit an answer in challenges, practice, a battle, or Bug Hunter to reset the timer. Browsing, signing in, and spinning do not count.</p>{data?.inactivityDue&&<small>{Date.parse(data.inactivityDue)<=Date.parse(data.serverNow)?"Inactivity penalty settled. Participate to begin a new 48-hour window.":`Next activity due: ${data.inactivityDue.slice(0,16).replace("T"," ")} UTC`}</small>}</article><p>XP cannot fall below zero. Ranks can go down when XP is lost. Shards and installed laboratory equipment are kept.</p><a className="btn cyan outline" href="/challenges">Stay active · Start a challenge →</a></aside></div>
 <section className={s.ladder}><div><span className={s.eyebrow}>19 BADGES · ONE MASTERPIECE</span><h2>Your path through the ranks</h2></div><div className={s.rankGrid}>{RANKS.map(r=><article key={r.name} data-unlocked={data&&data.xp>=r.xp?true:undefined} data-current={data?.rank.name===r.name?true:undefined}><RankBadge xp={r.xp}/><small>{r.xp.toLocaleString()} XP</small><span>{data?.rank.name===r.name?"CURRENT RANK":data&&data.xp>=r.xp?"REACHED":"LOCKED"}</span></article>)}</div></section>
 <section className={s.ledger}><h2>Rewards & deductions</h2>{data?.events.length?<div className={s.entries}>{data.events.map((e,i)=><article key={i}><div><b>{e.label}</b><small>{e.created_at.slice(0,16).replace("T"," ")} UTC</small></div><strong data-negative={e.xp_delta<0?true:undefined}>{e.xp_delta!==0?`${e.xp_delta>0?"+":""}${e.xp_delta} XP`:e.shards?`+${e.shards} Shards`:"0 XP"}</strong></article>)}</div>:<p>Your bonuses, spins, and deductions will appear here.</p>}</section>{!data&&<button onClick={()=>load().catch(e=>setMessage(e.message))}>Retry loading rewards</button>}</>}
