"use client";
import {useEffect,useState} from "react";
import {NPCS} from "../../lib/npcs";
import {LAB_ITEMS} from "../../lib/laboratory";
import Avatar from "../components/Avatar";
import s from "./laboratory.module.css";
type Lab={character:string;earned:number;balance:number;unlocks:string[]};
export default function Laboratory(){const [lab,setLab]=useState<Lab|null>(null),[tab,setTab]=useState("equipment"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/laboratory"),d=await r.json() as Lab&{error?:string};if(!r.ok)throw Error(d.error);setLab(d)}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 async function act(payload:Record<string,string>){setBusy(true);setMessage("");try{const r=await fetch("/api/laboratory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json() as {error?:string};await load();if(!r.ok)throw Error(d.error);setMessage(payload.action==="character"?"Character selected. Your laboratory is saved.":"Equipment installed. Your laboratory is saved.")}catch(e){setMessage(e instanceof Error?e.message:"Connection lost. Please retry.")}finally{setBusy(false)}}
 const character=NPCS.find(n=>n.slug===lab?.character)||NPCS[5];
 return <><div className={s.hud}><div><span className={s.eyebrow}>PERSONAL SANCTUARY</span><strong>{character.name}&apos;s keep</strong></div><div className={s.wallet}><span aria-hidden="true">◈</span><strong>{lab?lab.balance:"—"}</strong><span>Aether Shards<small>Earned through challenges</small></span></div><a href="/challenges" className={s.quest}>Start a challenge →</a></div>
 <div className={s.scene} aria-label={`Your laboratory. ${lab?.unlocks.length||0} of 4 equipment upgrades installed.`}><div className={s.arch}/><div className={s.window}/><div className={s.gridFloor}/><div className={`${s.reactor} ${lab?.unlocks.includes("reactor")?s.powered:""}`}><div/><span>{lab?.unlocks.includes("reactor")?"CORE ONLINE":"CORE DORMANT"}</span></div><div className={`${s.archive} ${lab?.unlocks.includes("archive")?s.powered:""}`}><i/><i/><i/><span>RUNIC ARCHIVE</span></div><div className={`${s.beacon} ${lab?.unlocks.includes("beacon")?s.powered:""}`}><b>ϟ</b><span>STORM BEACON</span></div>{lab?.unlocks.includes("crest")&&<div className={s.crest}>♜</div>}<div className={s.hero}><Avatar hue={character.hue} size={112} label={character.name}/><span>{character.name}</span></div><div className={s.sceneCaption}><span>RESEARCH CHAMBER / 01</span><span>{lab?.unlocks.length||0} / 4 systems unlocked</span></div></div>
 {message&&<div className={s.message} role="status">{message}{!lab&&<button onClick={()=>load().catch(e=>setMessage(e.message))}>Retry</button>}</div>}
 <div className={s.tabs} role="group" aria-label="Laboratory sections"><button aria-pressed={tab==="equipment"} onClick={()=>setTab("equipment")}>01 · Equipment</button><button aria-pressed={tab==="characters"} onClick={()=>setTab("characters")}>02 · Characters</button><a href="/rewards">◈ Daily spin & prizes →</a><span>Progress is saved to your account</span></div>
 {tab==="equipment"?<><div className={s.intro}><h2>Turn knowledge into power.</h2><p>Every first-time challenge reward grants 1 Aether Shard per 5 XP, rounded down. Replays do not pay again. Equipment changes your laboratory&apos;s appearance; it gives no battle advantage.</p></div><div className={s.cards}>{LAB_ITEMS.map(item=>{const owned=lab?.unlocks.includes(item.id);return <article key={item.id} className={`${s.card} ${owned?s.owned:""}`}><span className={s.sigil}>{item.symbol}</span><span className={s.eyebrow}>{owned?"INSTALLED":"LAB UPGRADE"}</span><h3>{item.name}</h3><p>{item.description}</p><button disabled={!lab||busy||owned||lab.balance<item.cost} onClick={()=>act({action:"unlock",item:item.id})}>{owned?"Installed ✓":`Install · ${item.cost} ◈`}</button>{lab&&!owned&&lab.balance<item.cost&&<small>{item.cost-lab.balance} more shards needed</small>}</article>})}</div></>:<><div className={s.intro}><h2>Choose who you become.</h2><p>All six characters are available from the start. Your selection is cosmetic and can be changed freely; NPC rival difficulty remains separate.</p></div><div className={s.cards}>{NPCS.map((n,i)=><article key={n.slug} className={`${s.card} ${lab?.character===n.slug?s.owned:""}`}><div className={s.portrait}><Avatar hue={n.hue} size={112} label={n.name}/></div><span className={s.eyebrow}>{["House of Frost","House of Storms","House of Roses","House of Thorns","House of Embers","House of Midnight"][i]}</span><h3>{n.name}</h3><p>{n.taunt}</p><button aria-pressed={lab?.character===n.slug} disabled={!lab||busy||lab.character===n.slug} onClick={()=>act({action:"character",character:n.slug})}>{lab?.character===n.slug?"Selected ✓":"Choose character"}</button></article>)}</div></>}
 </>}
