"use client";
import {useState} from "react";

const paths={swords:<><path d="m5 4 15 15M14 4h6v6M10 14l-6 6M4 14l6 6"/><path d="m20 4-6 6"/></>,bolt:<path d="m13 2-8 12h7l-1 8 8-12h-7z"/>,users:<><path d="M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 20v-2a4 4 0 0 0-3-3.9"/></>,target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="m15 9 6-6"/></>,brain:<><path d="M9.5 4.5A3.5 3.5 0 0 0 6 8v.3A3.6 3.6 0 0 0 4 15a3 3 0 0 0 3 3h2.5M14.5 4.5A3.5 3.5 0 0 1 18 8v.3a3.6 3.6 0 0 1 2 6.7 3 3 0 0 1-3 3h-2.5M12 3v18"/></>,shield:<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>};
function Icon({name}:{name:keyof typeof paths}){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
function NeonButton({children,tone="cyan",onClick}:{children:React.ReactNode;tone?:"cyan"|"pink";onClick?:()=>void}){return <button className={`neon-button ${tone}`} onClick={onClick}>{children}</button>}
function ArenaPanel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`arena-panel ${className}`}>{children}</section>}

const modes=[
 {icon:"target" as const,title:"Solo Practice",copy:"Sharpen weak areas with adaptive challenges and instant explanations.",tag:"TRAIN",tone:"cyan"},
 {icon:"brain" as const,title:"Battle Bots",copy:"Face believable rivals from Rookie to Legend. Learn every round.",tag:"SIMULATE",tone:"purple"},
 {icon:"users" as const,title:"Live Arena",copy:"Challenge friends in server-timed, head-to-head coding battles.",tag:"COMPETE",tone:"pink"}
];

export default function Home(){
 const [toast,setToast]=useState(""); const ping=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 return <main>
  <header className="topbar"><a className="brand" href="#top"><img src="/assets/logo.png" alt="Clash of Errors"/></a><nav aria-label="Primary"><a href="#modes">Battle Modes</a><a href="#progress">Progression</a><a href="#coach">AI Coach</a></nav><div className="nav-actions"><button className="ghost" onClick={()=>ping("Profiles arrive in Milestone 2")}>Sign in</button><NeonButton onClick={()=>document.querySelector("#modes")?.scrollIntoView()}>Enter Arena</NeonButton></div></header>
  <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span/> SEASON 01 // ARENA ONLINE</div><h1>TURN ERRORS INTO <em>VICTORIES.</em></h1><p>Train smarter. Battle live. Master the code that used to break you.</p><div className="hero-actions"><NeonButton onClick={()=>document.querySelector("#modes")?.scrollIntoView()}><Icon name="swords"/> Start your first battle</NeonButton><NeonButton tone="pink" onClick={()=>ping("Demo arena queued for Milestone 3")}><Icon name="bolt"/> Watch the clash</NeonButton></div><div className="trust-row"><span><b>12K+</b> active coders</span><span><b>850K</b> bugs defeated</span><span><b>4.9/5</b> learner rating</span></div></div>
   <figure className="hero-art" aria-label="Live Clash of Errors coding battle"><img src="/assets/landing-reference.png" alt="Two players competing in a neon live coding arena with a leaderboard"/><figcaption><span className="live-dot">LIVE ARENA</span><b>CODE. CLASH. CONQUER.</b></figcaption></figure>
  </section>
  <section className="mode-section" id="modes"><div className="section-heading"><div><span className="kicker">CHOOSE YOUR PATH</span><h2>THREE WAYS TO GET <em>BETTER.</em></h2></div><p>Every match feeds one persistent learning profile—your skill, speed, and rank travel with you.</p></div><div className="mode-grid">{modes.map((m,i)=><ArenaPanel key={m.title} className={`mode-card ${m.tone}`}><span className="card-index">0{i+1}</span><div className="hex-icon"><Icon name={m.icon}/></div><span className="mode-tag">{m.tag}</span><h3>{m.title}</h3><p>{m.copy}</p><button onClick={()=>ping(`${m.title} is ready for its product milestone`)}>Explore mode <span>→</span></button></ArenaPanel>)}</div></section>
  <section className="progress-section" id="progress"><ArenaPanel className="rank-panel"><div className="rank-emblem"><Icon name="shield"/><span>III</span></div><div><span className="kicker">YOUR JOURNEY</span><h2>RISE THROUGH THE RANKS.</h2><p>Earn XP with every meaningful attempt. Master topics, protect your streak, and unlock achievements without grind.</p><div className="xp-label"><span>DIAMOND III</span><b>2,450 / 3,000 XP</b></div><div className="xp-bar"><i/></div></div><div className="stats"><div><b>78%</b><span>Accuracy</span></div><div><b>12</b><span>Day streak</span></div><div><b>7</b><span>Topics mastered</span></div></div></ArenaPanel></section>
  <section className="coach" id="coach"><div className="coach-orb"><Icon name="brain"/></div><div><span className="kicker">ADAPTIVE AI COACH</span><h2>EVERY MISTAKE BECOMES A <em>MOVE FORWARD.</em></h2><p>Get clear explanations, spot recurring patterns, and receive the next challenge that actually helps.</p></div><NeonButton onClick={()=>ping("AI coaching arrives in Milestone 10")}>See how coaching works</NeonButton></section>
  <footer><a className="brand compact" href="#top"><img src="/assets/mark.png" alt=""/><span>CLASH OF ERRORS</span></a><p>Battle. Code. Conquer.</p><span>© 2026 CLASH OF ERRORS</span></footer>{toast&&<div className="toast" role="status">{toast}</div>}
 </main>
}
