import {and,asc,eq} from "drizzle-orm";
import {getChatGPTUser} from "../../../chatgpt-auth";
import {getDb} from "../../../../db";
import {arenaAnswers,arenaBattleQuestions,arenaParticipants,arenas,questionOptions,questions} from "../../../../db/schema";
import {scoreAnswer} from "../../../../lib/scoring";

async function battleContext(code:string){const user=await getChatGPTUser();if(!user)return null;const db=await getDb(),[arena]=await db.select().from(arenas).where(eq(arenas.code,code.toUpperCase())).limit(1);if(!arena)return {db,user,arena:null,member:null};const [member]=await db.select().from(arenaParticipants).where(and(eq(arenaParticipants.arenaId,arena.id),eq(arenaParticipants.userId,user.userId))).limit(1);return {db,user,arena,member}}
function timing(startedAt:string,timeLimit:number,total:number){const elapsed=Math.max(0,Date.now()-Date.parse(startedAt)),roundMs=(timeLimit+3)*1000,index=Math.floor(elapsed/roundMs),within=elapsed%roundMs;return {elapsed,roundMs,index,phase:index>=total?"complete":within<timeLimit*1000?"answer":"reveal",remainingMs:index>=total?0:within<timeLimit*1000?timeLimit*1000-within:roundMs-within,responseMs:Math.min(timeLimit*1000,within)}}

export async function GET(_:Request,{params}:{params:Promise<{code:string}>}){try{const ctx=await battleContext((await params).code);if(!ctx)return Response.json({error:"Authentication required"},{status:401});if(!ctx.arena||!ctx.member)return Response.json({error:"Battle not found"},{status:404});if(!ctx.arena.startedAt)return Response.json({status:ctx.arena.status},{status:409});const battleQuestions=await ctx.db.select({id:arenaBattleQuestions.id,questionId:arenaBattleQuestions.questionId,position:arenaBattleQuestions.position,prompt:questions.prompt,code:questions.code,explanation:questions.explanation}).from(arenaBattleQuestions).innerJoin(questions,eq(arenaBattleQuestions.questionId,questions.id)).where(eq(arenaBattleQuestions.arenaId,ctx.arena.id)).orderBy(asc(arenaBattleQuestions.position));const clock=timing(ctx.arena.startedAt,ctx.arena.timeLimit,battleQuestions.length);if(clock.phase==="complete"&&ctx.arena.status!=="completed"){const now=new Date().toISOString();await ctx.db.update(arenas).set({status:"completed",completedAt:now,updatedAt:now}).where(eq(arenas.id,ctx.arena.id))}const standings=await ctx.db.select({id:arenaParticipants.id,displayName:arenaParticipants.displayName,avatar:arenaParticipants.avatar,score:arenaParticipants.score,correct:arenaParticipants.correct,streak:arenaParticipants.streak}).from(arenaParticipants).where(eq(arenaParticipants.arenaId,ctx.arena.id)).orderBy(asc(arenaParticipants.id));standings.sort((a,b)=>b.score-a.score||b.correct-a.correct);if(clock.phase==="complete")return Response.json({status:"completed",code:ctx.arena.code,title:ctx.arena.title,standings,questionCount:battleQuestions.length,scoringVersion:ctx.arena.scoringVersion});const current=battleQuestions[clock.index],options=await ctx.db.select({id:questionOptions.id,label:questionOptions.label,isCorrect:questionOptions.isCorrect}).from(questionOptions).where(eq(questionOptions.questionId,current.questionId)).orderBy(asc(questionOptions.position)),[answer]=await ctx.db.select().from(arenaAnswers).where(and(eq(arenaAnswers.participantId,ctx.member.id),eq(arenaAnswers.questionId,current.questionId))).limit(1);const reveal=clock.phase==="reveal"?{correctOptionId:options.find(o=>o.isCorrect)?.id,explanation:current.explanation}:null;return Response.json({status:"active",serverNow:Date.now(),phase:clock.phase,remainingMs:clock.remainingMs,questionIndex:clock.index,questionCount:battleQuestions.length,question:{id:current.questionId,prompt:current.prompt,code:current.code,options:options.map(o=>({id:o.id,label:o.label}))},answer:answer?{selectedOptionId:answer.selectedOptionId,isCorrect:answer.isCorrect,points:answer.points}:null,reveal,standings,participantId:ctx.member.id,timeLimit:ctx.arena.timeLimit})}catch{return Response.json({error:"Unable to synchronize battle"},{status:500})}}

export async function POST(request:Request,{params}:{params:Promise<{code:string}>}){try{const ctx=await battleContext((await params).code);if(!ctx)return Response.json({error:"Authentication required"},{status:401});if(!ctx.arena||!ctx.member||ctx.arena.status!=="active"||!ctx.arena.startedAt)return Response.json({error:"Battle is not active"},{status:409});const body=await request.json() as {questionId?:number;optionId?:number},battleQuestions=await ctx.db.select().from(arenaBattleQuestions).where(eq(arenaBattleQuestions.arenaId,ctx.arena.id)).orderBy(asc(arenaBattleQuestions.position)),clock=timing(ctx.arena.startedAt,ctx.arena.timeLimit,battleQuestions.length),current=battleQuestions[clock.index];if(clock.phase!=="answer"||!current||body.questionId!==current.questionId)return Response.json({error:"Submission window closed"},{status:409});const [option]=await ctx.db.select().from(questionOptions).where(and(eq(questionOptions.id,Number(body.optionId)),eq(questionOptions.questionId,current.questionId))).limit(1);if(!option)return Response.json({error:"Invalid answer option"},{status:400});const nextStreak=option.isCorrect?ctx.member.streak+1:0,points=scoreAnswer(option.isCorrect,clock.responseMs,nextStreak),now=new Date().toISOString();await ctx.db.insert(arenaAnswers).values({arenaId:ctx.arena.id,participantId:ctx.member.id,questionId:current.questionId,selectedOptionId:option.id,isCorrect:option.isCorrect,responseMs:clock.responseMs,points,streak:nextStreak,answeredAt:now});await ctx.db.update(arenaParticipants).set({score:ctx.member.score+points,correct:ctx.member.correct+(option.isCorrect?1:0),streak:nextStreak,lastSeenAt:now,status:"online"}).where(eq(arenaParticipants.id,ctx.member.id));return Response.json({accepted:true})}catch(error){if(error instanceof Error&&/unique|constraint/i.test(error.message))return Response.json({error:"Question already answered"},{status:409});return Response.json({error:"Unable to submit answer"},{status:500})}}
