"use client";
import {useEffect,useRef,useState} from "react";
type Question={id:number;prompt:string;code:string;options:{id:number;label:string}[]};
type SessionData={session:{questionCount:number;difficulty:string};progress:number;complete?:boolean;question?:Question;error?:string};
type Feedback={correct:boolean;correctOptionId:number;explanation:string;complete:boolean;xpEarned:number;error?:string};
export default function PracticeRunner({id}:{id:string}){
 const [data,setData]=useState<SessionData|null>(null),[selected,setSelected]=useState<number|null>(null),[feedback,setFeedback]=useState<Feedback|null>(null),[error,setError]=useState("");
 const started=useRef(0);
 async function load(){const response=await fetch(`/api/practice/session/${id}`),body=await response.json() as SessionData;if(response.ok){if(body.complete){location.href=`/practice/results/${id}`;return}setData(body);setSelected(null);setFeedback(null);started.current=Date.now()}else setError(body.error||"Unable to load practice")}
 useEffect(()=>{const controller=new AbortController();fetch(`/api/practice/session/${id}`,{signal:controller.signal}).then(async response=>({response,body:await response.json() as SessionData})).then(({response,body})=>{if(response.ok){if(body.complete){location.href=`/practice/results/${id}`;return}setData(body);started.current=Date.now()}else setError(body.error||"Unable to load practice")}).catch(reason=>{if(reason instanceof Error&&reason.name!=="AbortError")setError("Unable to load practice")});return()=>controller.abort()},[id]);
 async function submit(){if(selected===null||!data?.question)return;const response=await fetch(`/api/practice/session/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionId:data.question.id,optionId:selected,responseMs:Date.now()-started.current})}),body=await response.json() as Feedback;if(response.ok)setFeedback(body);else setError(body.error||"Unable to submit answer")}
 function next(){if(feedback?.complete)location.href=`/practice/results/${id}`;else void load()}
 if(error)return <div className="runner-state"><b>SESSION ERROR</b><p>{error}</p><a href="/practice">Return to setup</a></div>;
 if(!data?.question)return <div className="runner-state">Loading challenge...</div>;
 const q=data.question,progress=data.progress+1;
 return <div className="practice-runner"><header className="runner-hud"><a href="/dashboard">← Exit</a><div><span>QUESTION {progress} / {data.session.questionCount}</span><div><i style={{width:`${progress/data.session.questionCount*100}%`}}/></div></div><b>{data.session.difficulty}</b></header><section className="question-stage"><div className="question-meta"><span>SELECT THE CORRECT ANSWER</span><b>+15 XP</b></div><h1>{q.prompt}</h1>{q.code&&<pre><code>{q.code}</code></pre>}<div className="answer-list">{q.options.map((o,i)=>{const state=feedback?(o.id===feedback.correctOptionId?"correct":o.id===selected?"wrong":""):o.id===selected?"selected":"";return <button disabled={!!feedback} className={state} key={o.id} onClick={()=>setSelected(o.id)}><span>{String.fromCharCode(65+i)}</span>{o.label}</button>})}</div>{feedback&&<aside className={`answer-feedback ${feedback.correct?"correct":"wrong"}`}><span>{feedback.correct?"CORRECT":"NOT QUITE"}</span><p>{feedback.explanation}</p></aside>}<button className="btn cyan solid runner-action" disabled={selected===null} onClick={feedback?next:submit}>{feedback?(feedback.complete?"View results":"Next question"):"Lock answer"}</button></section></div>
}
