import {desc,inArray} from "drizzle-orm";
import {getChatGPTUser} from "../../chatgpt-auth";
import {getDb} from "../../../db";
import {questionOptions,questions,topics,users} from "../../../db/schema";

const clean=(v:unknown,max:number)=>typeof v==="string"?v.trim().replace(/[<>]/g,"").slice(0,max):"";
async function identity(){const user=await getChatGPTUser();if(!user)return null;const now=new Date().toISOString(),db=await getDb();await db.insert(users).values({id:user.userId,email:user.email,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:users.id,set:{email:user.email,updatedAt:now}});return user}
export async function GET(){try{if(!await identity())return Response.json({error:"Authentication required"},{status:401});const db=await getDb();const [topicRows,questionRows]=await Promise.all([db.select().from(topics),db.select().from(questions).orderBy(desc(questions.createdAt)).limit(100)]);const questionIds=questionRows.map(({id})=>id);const optionRows=questionIds.length?await db.select().from(questionOptions).where(inArray(questionOptions.questionId,questionIds)):[];return Response.json({topics:topicRows,questions:questionRows.map(question=>({...question,options:optionRows.filter(option=>option.questionId===question.id)}))})}catch{return Response.json({error:"Question bank unavailable"},{status:503})}}
export async function POST(request:Request){try{const user=await identity();if(!user)return Response.json({error:"Authentication required"},{status:401});const body=await request.json() as Record<string,unknown>,prompt=clean(body.prompt,500),explanation=clean(body.explanation,1000),difficulty=clean(body.difficulty,12),code=clean(body.code,1500),topicId=Number(body.topicId),options=Array.isArray(body.options)?body.options.map(v=>clean(v,180)).filter(Boolean):[],correctIndex=Number(body.correctIndex);if(prompt.length<10||explanation.length<10||!Number.isInteger(topicId)||options.length<2||options.length>6||correctIndex<0||correctIndex>=options.length)return Response.json({error:"Complete the prompt, explanation, topic and 2-6 answers"},{status:400});const db=await getDb(),now=new Date().toISOString();const [question]=await db.insert(questions).values({topicId,authorId:user.userId,prompt,code,explanation,difficulty:["easy","medium","hard"].includes(difficulty)?difficulty:"medium",status:"draft",createdAt:now,updatedAt:now}).returning();await db.insert(questionOptions).values(options.map((label,position)=>({questionId:question.id,label,position,isCorrect:position===correctIndex})));return Response.json({question},{status:201})}catch{return Response.json({error:"Unable to create question"},{status:500})}}
