import {eq} from "drizzle-orm";
import {getChatGPTUser} from "../../chatgpt-auth";
import {getDb} from "../../../db";
import {profiles,users} from "../../../db/schema";

const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().replace(/[<>]/g,"").slice(0,max):"";
async function ensureProfile(){const identity=await getChatGPTUser();if(!identity)return null;const db=await getDb(),now=new Date().toISOString();await db.insert(users).values({id:identity.userId,email:identity.email,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:users.id,set:{email:identity.email,updatedAt:now}});await db.insert(profiles).values({userId:identity.userId,displayName:identity.fullName||identity.email.split("@")[0],avatar:(identity.fullName||identity.email).slice(0,2).toUpperCase(),updatedAt:now}).onConflictDoNothing();const [profile]=await db.select().from(profiles).where(eq(profiles.userId,identity.userId)).limit(1);return {identity,profile}}
export async function GET(){try{const result=await ensureProfile();return result?Response.json(result):Response.json({error:"Authentication required"},{status:401})}catch{return Response.json({error:"Profile storage is temporarily unavailable"},{status:503})}}
export async function PATCH(request:Request){try{const result=await ensureProfile();if(!result)return Response.json({error:"Authentication required"},{status:401});const body=await request.json() as {displayName?:unknown;bio?:unknown},displayName=clean(body.displayName,32),bio=clean(body.bio,160);if(displayName.length<2)return Response.json({error:"Display name must be at least 2 characters"},{status:400});const db=await getDb();await db.update(profiles).set({displayName,bio,avatar:displayName.slice(0,2).toUpperCase(),updatedAt:new Date().toISOString()}).where(eq(profiles.userId,result.identity.userId));const [profile]=await db.select().from(profiles).where(eq(profiles.userId,result.identity.userId)).limit(1);return Response.json({profile})}catch{return Response.json({error:"Unable to update the profile"},{status:500})}}
